version: "3.7"

services:
  pgdb:
    image: postgres:10.22-alpine
    container_name: pgdb
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5435:5432"

volumes:
  pgdata:
    external: true
